gantt
    title 图5-1 最优自适应物理时序 (基准HGW标定) - 【横轴单位：毫秒 ms】
    dateFormat  x
    axisFormat  %S.%L

    section 核心逻辑状态
    阶段0 基础蓄压 :a1, 0, 2800
    阶段1 高频蓄雾 :a2, 2800, 3018
    阶段2a 阀芯起飞 :a3, 3018, 3025
    阶段2b 精准爆破 :a4, 3025, 3075
    阶段3 清风扫膛 :a5, 3075, 3125

    section 硬件执行器动作
    气泵 (Pump)           :b1, 0, 3025
    雾化片 (Atomizer)     :b2, 2800, 3075
    电磁阀 (Valve)        :b3, 3018, 3125
    触发激光 (Laser)      :b4, 3025, 3125
